
export const SET_LIGHT_THEME = "SET_LIGHT_THEME"
export const SET_DARK_THEME = "SET_DARK_THEME"

export const lightTheme="light"
export const darkTheme ='dark'

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';


export const CREATE_USER_BEGIN = 'CREATE_USER_BEGIN';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const FETCH_ORG_BEGIN = 'FETCH_ORG_BEGIN';
export const FETCH_ORG_SUCCESS = 'FETCH_ORG_SUCCESS';
export const FETCH_ORG_FAILURE = 'FETCH_ORG_FAILURE';

export const CREATE_ORG_BEGIN = 'CREATE_ORG_BEGIN';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
export const CREATE_ORG_FAILURE = 'CREATE_ORG_FAILURE';

export const CHANGE_CURRENT_ORG = 'CHANGE_CURRENT_ORG'

export const FETCH_MEMBERS_BEGIN = 'FETCH_MEMBERS_BEGIN';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const INVITE_MEMBERS_BEGIN = 'FETCH_MEMBERS_BEGIN';
export const INVITE_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const INVITE_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const FETCH_PLANS_BEGIN = 'FETCH_PLANS_BEGIN';
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS';
export const FETCH_PLANS_FAILURE = 'FETCH_PLANS_FAILURE';

export const FETCH_WALLET_BEGIN = 'FETCH_WALLET_BEGIN';
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS';
export const FETCH_WALLET_FAILURE = 'FETCH_WALLET_FAILURE';